apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logic-service.fullname" . }}
  labels:
    {{- include "logic-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "logic-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        commitSha: {{ .Values.commitSha }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "logic-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: logic-service
          image: gitlab.stud.atlantis.ugent.be:5050/devops-2021/devops-team3/logic-service:latest
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
            {{- end }}
          env:
            - name: SECURE_ENDPOINTS
              value: "{{ .Values.logicService.secureEndpoints }}"
            - name: SECURE_KEY
              value: "{{ .Values.logicService.secureKey }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: '/app/gamestate'
              name: 'gamestate'
      volumes:
        - name: 'gamestate'
          persistentVolumeClaim:
            claimName: {{ include "logic-service.fullname" . }}-pvc
