adminPassword: leukhondje

rbac:
  create: false
  pspEnabled: false
serviceAccount:
  create: false

ingress:
  enabled: true
  hosts:
     - devops-proxy.atlantis.ugent.be
  path: /grafana/devops-team3

grafana.ini:
  server:
    domain: devops-proxy.atlantis.ugent.be
    root_url: "%(protocol)s://%(domain)s/grafana/devops-team3"
    serve_from_sub_path: true

persistence:
  enabled: true
  size: 4Gi
  storageClassName: k8s-stud-storage